services:
  sqaaas-api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: sqaaas-api
    ports:
      - 8082:8082
    volumes:
      - ../etc:/etc/sqaaas
    command: ['-p 8082', '-c /etc/sqaaas/sqaaas.ini.local', '-d']
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    environment:
    - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    privileged: true
    user: root
    ports:
     - 8080:8080
     - 50000:50000
    networks:
      default:
        aliases:
          - jenkins.sqaaas.local
