// SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project <sqaaas@ibergrid.eu>
// SPDX-FileContributor: Pablo Orviz <orviz@ifca.unican.es>
//
// SPDX-License-Identifier: GPL-3.0-only

@Library(['github.com/indigo-dc/jenkins-pipeline-library@2.1.1']) _

def projectConfig

pipeline {
    agent any

    stages {
        {%- for config_data in config_data_list %}
        stage('SQA baseline criterion: {{ config_data.data_json.sqa_criteria |list |join(" & " ) }}') {
            when {
                anyOf {
                    expression { currentBuild.previousCompletedBuild == null }
                    changeset ".sqa/*"
                    changeset "Jenkinsfile"
                }
                {%- if config_data.data_when %}
                {%- for k,v in config_data.data_when.items() %}
                {%- if k == 'branch' %}
                branch pattern: '{{ v.pattern }}', comparator: '{{ v.comparator }}'
                {%- elif k == 'building_tag' and v %}
                buildingTag()
                {%- endif %}
                {%- endfor %}
                {%- endif %}
            }
            steps {
                script {
                    projectConfig = pipelineConfig(
                        configFile: '{{ config_data.file_name }}',
                        scmConfigs: [ localBranch: true ],
                        validatorDockerImage: 'eoscsynergy/jpl-validator:2.4.0'
                    )
                    buildStages(projectConfig)
                }
            }
            post {
                cleanup {
                    cleanWs()
                }
            }
        }
        {%- endfor %}
    }
}
