# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.assessment_output_data import AssessmentOutputData
from openapi_server import util


class AssessmentOutputReport(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, valid: bool=False, data: AssessmentOutputData=None):
        """AssessmentOutputReport - a model defined in OpenAPI

        :param valid: The valid of this AssessmentOutputReport.
        :param data: The data of this AssessmentOutputReport.
        """
        self.openapi_types = {
            'valid': bool,
            'data': AssessmentOutputData
        }

        self.attribute_map = {
            'valid': 'valid',
            'data': 'data'
        }

        self._valid = valid
        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AssessmentOutputReport':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AssessmentOutput_report of this AssessmentOutputReport.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def valid(self):
        """Gets the valid of this AssessmentOutputReport.


        :return: The valid of this AssessmentOutputReport.
        :rtype: bool
        """
        return self._valid

    @valid.setter
    def valid(self, valid):
        """Sets the valid of this AssessmentOutputReport.


        :param valid: The valid of this AssessmentOutputReport.
        :type valid: bool
        """

        self._valid = valid

    @property
    def data(self):
        """Gets the data of this AssessmentOutputReport.


        :return: The data of this AssessmentOutputReport.
        :rtype: AssessmentOutputData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this AssessmentOutputReport.


        :param data: The data of this AssessmentOutputReport.
        :type data: AssessmentOutputData
        """

        self._data = data
