# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AssessmentOutputMeta(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, version: str = None, report_json_url: str = None):
        """AssessmentOutputMeta - a model defined in OpenAPI

        :param version: The version of this AssessmentOutputMeta.
        :param report_json_url: The report_json_url of this AssessmentOutputMeta.
        """
        self.openapi_types = {"version": str, "report_json_url": str}

        self.attribute_map = {
            "version": "version",
            "report_json_url": "report_json_url",
        }

        self._version = version
        self._report_json_url = report_json_url

    @classmethod
    def from_dict(cls, dikt: dict) -> "AssessmentOutputMeta":
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AssessmentOutput_meta of this AssessmentOutputMeta.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def version(self):
        """Gets the version of this AssessmentOutputMeta.

        Version of the API spec the generated report payload is based on

        :return: The version of this AssessmentOutputMeta.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this AssessmentOutputMeta.

        Version of the API spec the generated report payload is based on

        :param version: The version of this AssessmentOutputMeta.
        :type version: str
        """

        self._version = version

    @property
    def report_json_url(self):
        """Gets the report_json_url of this AssessmentOutputMeta.

        location in the build repository with the resultant assessment report (JSON format)

        :return: The report_json_url of this AssessmentOutputMeta.
        :rtype: str
        """
        return self._report_json_url

    @report_json_url.setter
    def report_json_url(self, report_json_url):
        """Sets the report_json_url of this AssessmentOutputMeta.

        location in the build repository with the resultant assessment report (JSON format)

        :param report_json_url: The report_json_url of this AssessmentOutputMeta.
        :type report_json_url: str
        """

        self._report_json_url = report_json_url
