# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.assessment_output_tool_ci import AssessmentOutputToolCI
from openapi_server import util


class AssessmentOutputValidatorTool(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, ci: AssessmentOutputToolCI=None, level: str=None):
        """AssessmentOutputValidatorTool - a model defined in OpenAPI

        :param name: The name of this AssessmentOutputValidatorTool.
        :param ci: The ci of this AssessmentOutputValidatorTool.
        :param level: The level of this AssessmentOutputValidatorTool.
        """
        self.openapi_types = {
            'name': str,
            'ci': AssessmentOutputToolCI,
            'level': str
        }

        self.attribute_map = {
            'name': 'name',
            'ci': 'ci',
            'level': 'level'
        }

        self._name = name
        self._ci = ci
        self._level = level

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AssessmentOutputValidatorTool':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AssessmentOutputValidatorTool of this AssessmentOutputValidatorTool.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this AssessmentOutputValidatorTool.


        :return: The name of this AssessmentOutputValidatorTool.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AssessmentOutputValidatorTool.


        :param name: The name of this AssessmentOutputValidatorTool.
        :type name: str
        """

        self._name = name

    @property
    def ci(self):
        """Gets the ci of this AssessmentOutputValidatorTool.


        :return: The ci of this AssessmentOutputValidatorTool.
        :rtype: AssessmentOutputToolCI
        """
        return self._ci

    @ci.setter
    def ci(self, ci):
        """Sets the ci of this AssessmentOutputValidatorTool.


        :param ci: The ci of this AssessmentOutputValidatorTool.
        :type ci: AssessmentOutputToolCI
        """

        self._ci = ci

    @property
    def level(self):
        """Gets the level of this AssessmentOutputValidatorTool.


        :return: The level of this AssessmentOutputValidatorTool.
        :rtype: str
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this AssessmentOutputValidatorTool.


        :param level: The level of this AssessmentOutputValidatorTool.
        :type level: str
        """
        allowed_values = ["REQUIRED", "RECOMMENDED", "OPTIONAL"]  # noqa: E501
        if level not in allowed_values:
            raise ValueError(
                "Invalid value for `level` ({0}), must be one of {1}"
                .format(level, allowed_values)
            )

        self._level = level
