# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.assessment_output_badge import AssessmentOutputBadge
from openapi_server.models.assessment_output_report_value import AssessmentOutputReportValue
from openapi_server.models.assessment_output_repository import AssessmentOutputRepository
from openapi_server import util


class AssessmentOutput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, version: str=None, repository: List[AssessmentOutputRepository]=None, report: Dict[str, AssessmentOutputReportValue]=None, badge: AssessmentOutputBadge=None):
        """AssessmentOutput - a model defined in OpenAPI

        :param version: The version of this AssessmentOutput.
        :param repository: The repository of this AssessmentOutput.
        :param report: The report of this AssessmentOutput.
        :param badge: The badge of this AssessmentOutput.
        """
        self.openapi_types = {
            'version': str,
            'repository': List[AssessmentOutputRepository],
            'report': Dict[str, AssessmentOutputReportValue],
            'badge': AssessmentOutputBadge
        }

        self.attribute_map = {
            'version': 'version',
            'repository': 'repository',
            'report': 'report',
            'badge': 'badge'
        }

        self._version = version
        self._repository = repository
        self._report = report
        self._badge = badge

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AssessmentOutput':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AssessmentOutput of this AssessmentOutput.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def version(self):
        """Gets the version of this AssessmentOutput.

        Version of the API spec the generated report payload is based on

        :return: The version of this AssessmentOutput.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this AssessmentOutput.

        Version of the API spec the generated report payload is based on

        :param version: The version of this AssessmentOutput.
        :type version: str
        """

        self._version = version

    @property
    def repository(self):
        """Gets the repository of this AssessmentOutput.

        Details about the (code, data) repository

        :return: The repository of this AssessmentOutput.
        :rtype: List[AssessmentOutputRepository]
        """
        return self._repository

    @repository.setter
    def repository(self, repository):
        """Sets the repository of this AssessmentOutput.

        Details about the (code, data) repository

        :param repository: The repository of this AssessmentOutput.
        :type repository: List[AssessmentOutputRepository]
        """

        self._repository = repository

    @property
    def report(self):
        """Gets the report of this AssessmentOutput.


        :return: The report of this AssessmentOutput.
        :rtype: Dict[str, AssessmentOutputReportValue]
        """
        return self._report

    @report.setter
    def report(self, report):
        """Sets the report of this AssessmentOutput.


        :param report: The report of this AssessmentOutput.
        :type report: Dict[str, AssessmentOutputReportValue]
        """

        self._report = report

    @property
    def badge(self):
        """Gets the badge of this AssessmentOutput.


        :return: The badge of this AssessmentOutput.
        :rtype: AssessmentOutputBadge
        """
        return self._badge

    @badge.setter
    def badge(self, badge):
        """Sets the badge of this AssessmentOutput.


        :param badge: The badge of this AssessmentOutput.
        :type badge: AssessmentOutputBadge
        """

        self._badge = badge
