# SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project <sqaaas@ibergrid.eu>
# SPDX-FileContributor: Pablo Orviz <orviz@ifca.unican.es>
#
# SPDX-License-Identifier: GPL-3.0-only

# coding: utf-8

from datetime import date, datetime
from typing import Dict, List, Type

from openapi_server import util
from openapi_server.models.base_model_ import Model
from openapi_server.models.tool import Tool


class AssessmentFAIR(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, fair_tool: Tool = None):
        """AssessmentFAIR - a model defined in OpenAPI

        :param fair_tool: The fair_tool of this AssessmentFAIR.
        """
        self.openapi_types = {"fair_tool": Tool}

        self.attribute_map = {"fair_tool": "fair_tool"}

        self._fair_tool = fair_tool

    @classmethod
    def from_dict(cls, dikt: dict) -> "AssessmentFAIR":
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AssessmentFAIR of this AssessmentFAIR.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def fair_tool(self):
        """Gets the fair_tool of this AssessmentFAIR.


        :return: The fair_tool of this AssessmentFAIR.
        :rtype: Tool
        """
        return self._fair_tool

    @fair_tool.setter
    def fair_tool(self, fair_tool):
        """Sets the fair_tool of this AssessmentFAIR.


        :param fair_tool: The fair_tool of this AssessmentFAIR.
        :type fair_tool: Tool
        """

        self._fair_tool = fair_tool
