# SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project <sqaaas@ibergrid.eu>
#
# SPDX-License-Identifier: GPL-3.0-only

# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class BadgeAssertionRecipient(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, identity: str=None, hashed: bool=None, type: str=None, plaintext_identity: str=None):
        """BadgeAssertionRecipient - a model defined in OpenAPI

        :param identity: The identity of this BadgeAssertionRecipient.
        :param hashed: The hashed of this BadgeAssertionRecipient.
        :param type: The type of this BadgeAssertionRecipient.
        :param plaintext_identity: The plaintext_identity of this BadgeAssertionRecipient.
        """
        self.openapi_types = {
            'identity': str,
            'hashed': bool,
            'type': str,
            'plaintext_identity': str
        }

        self.attribute_map = {
            'identity': 'identity',
            'hashed': 'hashed',
            'type': 'type',
            'plaintext_identity': 'plaintextIdentity'
        }

        self._identity = identity
        self._hashed = hashed
        self._type = type
        self._plaintext_identity = plaintext_identity

    @classmethod
    def from_dict(cls, dikt: dict) -> 'BadgeAssertionRecipient':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The BadgeAssertion_recipient of this BadgeAssertionRecipient.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def identity(self):
        """Gets the identity of this BadgeAssertionRecipient.


        :return: The identity of this BadgeAssertionRecipient.
        :rtype: str
        """
        return self._identity

    @identity.setter
    def identity(self, identity):
        """Sets the identity of this BadgeAssertionRecipient.


        :param identity: The identity of this BadgeAssertionRecipient.
        :type identity: str
        """

        self._identity = identity

    @property
    def hashed(self):
        """Gets the hashed of this BadgeAssertionRecipient.


        :return: The hashed of this BadgeAssertionRecipient.
        :rtype: bool
        """
        return self._hashed

    @hashed.setter
    def hashed(self, hashed):
        """Sets the hashed of this BadgeAssertionRecipient.


        :param hashed: The hashed of this BadgeAssertionRecipient.
        :type hashed: bool
        """

        self._hashed = hashed

    @property
    def type(self):
        """Gets the type of this BadgeAssertionRecipient.


        :return: The type of this BadgeAssertionRecipient.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this BadgeAssertionRecipient.


        :param type: The type of this BadgeAssertionRecipient.
        :type type: str
        """
        allowed_values = ["email", "openBadgeId", "telephone", "url"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def plaintext_identity(self):
        """Gets the plaintext_identity of this BadgeAssertionRecipient.


        :return: The plaintext_identity of this BadgeAssertionRecipient.
        :rtype: str
        """
        return self._plaintext_identity

    @plaintext_identity.setter
    def plaintext_identity(self, plaintext_identity):
        """Sets the plaintext_identity of this BadgeAssertionRecipient.


        :param plaintext_identity: The plaintext_identity of this BadgeAssertionRecipient.
        :type plaintext_identity: str
        """

        self._plaintext_identity = plaintext_identity
