# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.agent import Agent
from openapi_server.models.tool import Tool
from openapi_server import util


class CriterionWorkflow(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, agent: Agent=None, tools: List[Tool]=None):
        """CriterionWorkflow - a model defined in OpenAPI

        :param id: The id of this CriterionWorkflow.
        :param agent: The agent of this CriterionWorkflow.
        :param tools: The tools of this CriterionWorkflow.
        """
        self.openapi_types = {
            'id': str,
            'agent': Agent,
            'tools': List[Tool]
        }

        self.attribute_map = {
            'id': 'id',
            'agent': 'agent',
            'tools': 'tools'
        }

        self._id = id
        self._agent = agent
        self._tools = tools

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CriterionWorkflow':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CriterionWorkflow of this CriterionWorkflow.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this CriterionWorkflow.

        ID of the criterion

        :return: The id of this CriterionWorkflow.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CriterionWorkflow.

        ID of the criterion

        :param id: The id of this CriterionWorkflow.
        :type id: str
        """

        self._id = id

    @property
    def agent(self):
        """Gets the agent of this CriterionWorkflow.


        :return: The agent of this CriterionWorkflow.
        :rtype: Agent
        """
        return self._agent

    @agent.setter
    def agent(self, agent):
        """Sets the agent of this CriterionWorkflow.


        :param agent: The agent of this CriterionWorkflow.
        :type agent: Agent
        """

        self._agent = agent

    @property
    def tools(self):
        """Gets the tools of this CriterionWorkflow.

        tools to run as workflow steps for the given criterion

        :return: The tools of this CriterionWorkflow.
        :rtype: List[Tool]
        """
        return self._tools

    @tools.setter
    def tools(self, tools):
        """Sets the tools of this CriterionWorkflow.

        tools to run as workflow steps for the given criterion

        :param tools: The tools of this CriterionWorkflow.
        :type tools: List[Tool]
        """

        self._tools = tools
