# SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project <sqaaas@ibergrid.eu>
# SPDX-FileContributor: Pablo Orviz <orviz@ifca.unican.es>
#
# SPDX-License-Identifier: GPL-3.0-only

# coding: utf-8

from datetime import date, datetime
from typing import Dict, List, Type

from openapi_server import util
from openapi_server.models.base_model_ import Model


class CriterionOutput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str = None, stdout: str = None):
        """CriterionOutput - a model defined in OpenAPI

        :param id: The id of this CriterionOutput.
        :param stdout: The stdout of this CriterionOutput.
        """
        self.openapi_types = {"id": str, "stdout": str}

        self.attribute_map = {"id": "id", "stdout": "stdout"}

        self._id = id
        self._stdout = stdout

    @classmethod
    def from_dict(cls, dikt: dict) -> "CriterionOutput":
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CriterionOutput of this CriterionOutput.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this CriterionOutput.


        :return: The id of this CriterionOutput.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CriterionOutput.


        :param id: The id of this CriterionOutput.
        :type id: str
        """

        self._id = id

    @property
    def stdout(self):
        """Gets the stdout of this CriterionOutput.


        :return: The stdout of this CriterionOutput.
        :rtype: str
        """
        return self._stdout

    @stdout.setter
    def stdout(self, stdout):
        """Sets the stdout of this CriterionOutput.


        :param stdout: The stdout of this CriterionOutput.
        :type stdout: str
        """

        self._stdout = stdout
