# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.criterion_description import CriterionDescription
from openapi_server.models.tool import Tool
from openapi_server import util


class Criterion(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, description: CriterionDescription=None, tools: Dict[str, List[Tool]]=None):
        """Criterion - a model defined in OpenAPI

        :param id: The id of this Criterion.
        :param description: The description of this Criterion.
        :param tools: The tools of this Criterion.
        """
        self.openapi_types = {
            'id': str,
            'description': CriterionDescription,
            'tools': Dict[str, List[Tool]]
        }

        self.attribute_map = {
            'id': 'id',
            'description': 'description',
            'tools': 'tools'
        }

        self._id = id
        self._description = description
        self._tools = tools

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Criterion':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Criterion of this Criterion.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Criterion.


        :return: The id of this Criterion.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Criterion.


        :param id: The id of this Criterion.
        :type id: str
        """

        self._id = id

    @property
    def description(self):
        """Gets the description of this Criterion.


        :return: The description of this Criterion.
        :rtype: CriterionDescription
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Criterion.


        :param description: The description of this Criterion.
        :type description: CriterionDescription
        """

        self._description = description

    @property
    def tools(self):
        """Gets the tools of this Criterion.


        :return: The tools of this Criterion.
        :rtype: Dict[str, List[Tool]]
        """
        return self._tools

    @tools.setter
    def tools(self, tools):
        """Sets the tools of this Criterion.


        :param tools: The tools of this Criterion.
        :type tools: Dict[str, List[Tool]]
        """

        self._tools = tools
