# SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project <sqaaas@ibergrid.eu>
#
# SPDX-License-Identifier: GPL-3.0-only

# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class GetPipelineJenkinsfileJepl200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, file_name: str=None, content: str=None):
        """GetPipelineJenkinsfileJepl200Response - a model defined in OpenAPI

        :param file_name: The file_name of this GetPipelineJenkinsfileJepl200Response.
        :param content: The content of this GetPipelineJenkinsfileJepl200Response.
        """
        self.openapi_types = {
            'file_name': str,
            'content': str
        }

        self.attribute_map = {
            'file_name': 'file_name',
            'content': 'content'
        }

        self._file_name = file_name
        self._content = content

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GetPipelineJenkinsfileJepl200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The get_pipeline_jenkinsfile_jepl_200_response of this GetPipelineJenkinsfileJepl200Response.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file_name(self):
        """Gets the file_name of this GetPipelineJenkinsfileJepl200Response.


        :return: The file_name of this GetPipelineJenkinsfileJepl200Response.
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this GetPipelineJenkinsfileJepl200Response.


        :param file_name: The file_name of this GetPipelineJenkinsfileJepl200Response.
        :type file_name: str
        """

        self._file_name = file_name

    @property
    def content(self):
        """Gets the content of this GetPipelineJenkinsfileJepl200Response.


        :return: The content of this GetPipelineJenkinsfileJepl200Response.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this GetPipelineJenkinsfileJepl200Response.


        :param content: The content of this GetPipelineJenkinsfileJepl200Response.
        :type content: str
        """

        self._content = content
