# SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project <sqaaas@ibergrid.eu>
# SPDX-FileContributor: Pablo Orviz <orviz@ifca.unican.es>
#
# SPDX-License-Identifier: GPL-3.0-only

# coding: utf-8

from datetime import date, datetime
from typing import Dict, List, Type

from openapi_server import util
from openapi_server.models.base_model_ import Model
from openapi_server.models.criterion_build_value import CriterionBuildValue


class GetPipelineConfigJepl200ResponseInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(
        self, file_name: str = None, content: Dict[str, CriterionBuildValue] = None
    ):
        """GetPipelineConfigJepl200ResponseInner - a model defined in OpenAPI

        :param file_name: The file_name of this GetPipelineConfigJepl200ResponseInner.
        :param content: The content of this GetPipelineConfigJepl200ResponseInner.
        """
        self.openapi_types = {
            "file_name": str,
            "content": Dict[str, CriterionBuildValue],
        }

        self.attribute_map = {"file_name": "file_name", "content": "content"}

        self._file_name = file_name
        self._content = content

    @classmethod
    def from_dict(cls, dikt: dict) -> "GetPipelineConfigJepl200ResponseInner":
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The get_pipeline_config_jepl_200_response_inner of this GetPipelineConfigJepl200ResponseInner.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file_name(self):
        """Gets the file_name of this GetPipelineConfigJepl200ResponseInner.


        :return: The file_name of this GetPipelineConfigJepl200ResponseInner.
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this GetPipelineConfigJepl200ResponseInner.


        :param file_name: The file_name of this GetPipelineConfigJepl200ResponseInner.
        :type file_name: str
        """

        self._file_name = file_name

    @property
    def content(self):
        """Gets the content of this GetPipelineConfigJepl200ResponseInner.

        Definition of software and service criteria to be run by the pipeline

        :return: The content of this GetPipelineConfigJepl200ResponseInner.
        :rtype: Dict[str, CriterionBuildValue]
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this GetPipelineConfigJepl200ResponseInner.

        Definition of software and service criteria to be run by the pipeline

        :param content: The content of this GetPipelineConfigJepl200ResponseInner.
        :type content: Dict[str, CriterionBuildValue]
        """

        self._content = content
