# SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project <sqaaas@ibergrid.eu>
#
# SPDX-License-Identifier: GPL-3.0-only

# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.je_pl_jenkinsfile_stages_inner_pipeline_config import JePLJenkinsfileStagesInnerPipelineConfig
from openapi_server.models.je_pl_jenkinsfile_stages_inner_when import JePLJenkinsfileStagesInnerWhen
from openapi_server import util


class JePLJenkinsfileStagesInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, when: JePLJenkinsfileStagesInnerWhen=None, pipeline_config: JePLJenkinsfileStagesInnerPipelineConfig=None):
        """JePLJenkinsfileStagesInner - a model defined in OpenAPI

        :param when: The when of this JePLJenkinsfileStagesInner.
        :param pipeline_config: The pipeline_config of this JePLJenkinsfileStagesInner.
        """
        self.openapi_types = {
            'when': JePLJenkinsfileStagesInnerWhen,
            'pipeline_config': JePLJenkinsfileStagesInnerPipelineConfig
        }

        self.attribute_map = {
            'when': 'when',
            'pipeline_config': 'pipeline_config'
        }

        self._when = when
        self._pipeline_config = pipeline_config

    @classmethod
    def from_dict(cls, dikt: dict) -> 'JePLJenkinsfileStagesInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The JePL_jenkinsfile_stages_inner of this JePLJenkinsfileStagesInner.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def when(self):
        """Gets the when of this JePLJenkinsfileStagesInner.


        :return: The when of this JePLJenkinsfileStagesInner.
        :rtype: JePLJenkinsfileStagesInnerWhen
        """
        return self._when

    @when.setter
    def when(self, when):
        """Sets the when of this JePLJenkinsfileStagesInner.


        :param when: The when of this JePLJenkinsfileStagesInner.
        :type when: JePLJenkinsfileStagesInnerWhen
        """

        self._when = when

    @property
    def pipeline_config(self):
        """Gets the pipeline_config of this JePLJenkinsfileStagesInner.


        :return: The pipeline_config of this JePLJenkinsfileStagesInner.
        :rtype: JePLJenkinsfileStagesInnerPipelineConfig
        """
        return self._pipeline_config

    @pipeline_config.setter
    def pipeline_config(self, pipeline_config):
        """Sets the pipeline_config of this JePLJenkinsfileStagesInner.


        :param pipeline_config: The pipeline_config of this JePLJenkinsfileStagesInner.
        :type pipeline_config: JePLJenkinsfileStagesInnerPipelineConfig
        """

        self._pipeline_config = pipeline_config
