# SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project <sqaaas@ibergrid.eu>
# SPDX-FileContributor: Pablo Orviz <orviz@ifca.unican.es>
#
# SPDX-License-Identifier: GPL-3.0-only

# coding: utf-8

from datetime import date, datetime
from typing import Dict, List, Type

from openapi_server import util
from openapi_server.models.base_model_ import Model


class ServiceDockerComposeValueImageRegistry(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, push: bool = None, credential_id: str = None):
        """ServiceDockerComposeValueImageRegistry - a model defined in OpenAPI

        :param push: The push of this ServiceDockerComposeValueImageRegistry.
        :param credential_id: The credential_id of this ServiceDockerComposeValueImageRegistry.
        """
        self.openapi_types = {"push": bool, "credential_id": str}

        self.attribute_map = {"push": "push", "credential_id": "credential_id"}

        self._push = push
        self._credential_id = credential_id

    @classmethod
    def from_dict(cls, dikt: dict) -> "ServiceDockerComposeValueImageRegistry":
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ServiceDockerCompose_value_image_registry of this ServiceDockerComposeValueImageRegistry.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def push(self):
        """Gets the push of this ServiceDockerComposeValueImageRegistry.


        :return: The push of this ServiceDockerComposeValueImageRegistry.
        :rtype: bool
        """
        return self._push

    @push.setter
    def push(self, push):
        """Sets the push of this ServiceDockerComposeValueImageRegistry.


        :param push: The push of this ServiceDockerComposeValueImageRegistry.
        :type push: bool
        """

        self._push = push

    @property
    def credential_id(self):
        """Gets the credential_id of this ServiceDockerComposeValueImageRegistry.


        :return: The credential_id of this ServiceDockerComposeValueImageRegistry.
        :rtype: str
        """
        return self._credential_id

    @credential_id.setter
    def credential_id(self, credential_id):
        """Sets the credential_id of this ServiceDockerComposeValueImageRegistry.


        :param credential_id: The credential_id of this ServiceDockerComposeValueImageRegistry.
        :type credential_id: str
        """

        self._credential_id = credential_id
