# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.tool import Tool
from openapi_server import util


class Step(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, tools: List[Tool]=None):
        """Step - a model defined in OpenAPI

        :param tools: The tools of this Step.
        """
        self.openapi_types = {
            'tools': List[Tool]
        }

        self.attribute_map = {
            'tools': 'tools'
        }

        self._tools = tools

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Step':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Step of this Step.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tools(self):
        """Gets the tools of this Step.

        set of tools to be used in the step

        :return: The tools of this Step.
        :rtype: List[Tool]
        """
        return self._tools

    @tools.setter
    def tools(self, tools):
        """Sets the tools of this Step.

        set of tools to be used in the step

        :param tools: The tools of this Step.
        :type tools: List[Tool]
        """

        self._tools = tools
